### ISSUE TITLE
Try upgrading Beam's bigtable-client-core to the latest 

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1028]
Try upgrading Beam's bigtable-client-core to the latest 1.12.1.

Let's see what happens.

go/beam-for-googlers

Steps:

- Does `./gradlew build` runs in locally without any modification?
  It failed:
  ```
  * What went wrong:
  Execution failed for task ':sdks:go:resolveBuildDependencies'.
  > Exception in resolution, message is:
    Cannot resolve dependency:google.golang.org/api: commit='386d4e5f4f92f86e6aec85985761bba4b938a2d5', urls=[https://code.googlesource.com/google-api-go-client]
    Resolution stack is:
    +- github.com/apache/beam/sdks/go
  ```
  Trying with Git tag `v2.16.0`... Same error. Now targeting only for Java `./gradlew -p sdks/java check` 
  Still failing one test. Asked in dev mailing list ([link](https://lists.apache.org/thread.html/8954a378c2e0451b8ddb3ba9ef7ce368af3086a2f217434e81168efb@%3Cdev.beam.apache.org%3E)).
  Bigtable-client-core is not recognized as outdated dependency. Why? Raised [BEAM-8621](https://issues.apache.org/jira/projects/BEAM/issues/BEAM-8621)
- Upgrade the bigtable-client-core version in BeamModulePlugin.groovy
- Run linkage checker enforcer rule with the locally modified beam-sdks-java-io-google-cloud-platform 
  This has dependency to the latest bigtable-client-core.
- Maybe I should try Beam with Bigtable tutorial?
- Read Contribution guide of Apache Beam project. -> Done
- Create PR. ->  https://github.com/apache/beam/pull/10144
- Any feedback?
 https://github.com/apache/beam/pull/10144#issuecomment-555703365
  > Confidence is based upon getting post commits passing and minimizing the number of version downgrades but since tests aren't comprehensive we either choose to risk the upgrade or leave it.

**Comment by suztomo** [comment]
Although presubmit checks are all green, the PR failed at "Java SDK Post Commit Tests " (Lukasz suggested post commit checks give more confidence).

https://builds.apache.org/job/beam_PostCommit_Java_PR/246/

```
java.lang.AbstractMethodError: com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.needsCredentials()Z
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.cloud.bigquery.storage.v1beta1.stub.EnhancedBigQueryStorageStub.create(EnhancedBigQueryStorageStub.java:89)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.<init>(BigQueryStorageClient.java:144)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.create(BigQueryStorageClient.java:125)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$StorageClientImpl.<init>(BigQueryServicesImpl.java:1028)
```

Other invocations than this PR look good. I'll investigate this error.

**Comment by suztomo** [comment]
I'm able to reproduce the error in IntelliJ: org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT
![image](https://user-images.githubusercontent.com/28604/69360598-dc3f1b00-0c58-11ea-8184-5f14153a45d6.png)

```
suztomo@suxtomo24:~/beam6$ ./gradlew -p sdks/java/io/google-cloud-platform integrationTest --tests org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT
Configuration on demand is an incubating feature.

> Task :sdks:java:io:google-cloud-platform:integrationTest FAILED

org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT > testQuery FAILED
    java.lang.AbstractMethodError at SpannerReadIT.java:106
    java.lang.NullPointerException at SpannerReadIT.java:234

org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT > testRead FAILED
    java.lang.AbstractMethodError at SpannerReadIT.java:106
    java.lang.NullPointerException at SpannerReadIT.java:234

org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT > testReadAllRecordsInDb FAILED
    java.lang.AbstractMethodError at SpannerReadIT.java:106
    java.lang.NullPointerException at SpannerReadIT.java:234

3 tests completed, 3 failed

FAILURE: Build failed with an exception.

```

**Comment by suztomo** [comment]
I updated BeamModulePlugin.groovy to have `gax_grpc                                    : "com.google.api:gax-grpc:1.48.0",`. Now it fails

```

io.grpc.ManagedChannelBuilder.disableServiceConfigLookUp()Lio/grpc/ManagedChannelBuilder;
java.lang.NoSuchMethodError: io.grpc.ManagedChannelBuilder.disableServiceConfigLookUp()Lio/grpc/ManagedChannelBuilder;
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:247)
```

**Comment by suztomo** [comment]
Now it ed4a95c fails with `NoClassDefFoundError`:

```
17:03:28 org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT > testReadPubsubMessageId FAILED
17:03:28     java.lang.NoClassDefFoundError
17:03:28         Caused by: java.lang.ClassNotFoundException
```

https://builds.apache.org/job/beam_PostCommit_Java_PR/253/console

Feeling it's making progress.

**Comment by suztomo** [comment]
Linkage Checker detects the NoClassDefFoundError. Nice.


```
suztomo@suxtomo24:~/beam6$  ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-google-cloud-platform :checkJavaLinkage
...
Class com.google.api.ClientProto is not found;
  referenced by 2 class files
    com.google.cloud.bigquery.storage.v1beta1.Storage (proto-google-cloud-bigquerystorage-v1beta1-0.76.0.jar)
    com.google.pubsub.v1.PubsubProto (proto-google-cloud-pubsub-v1-1.75.0.jar)
```

**Comment by suztomo** [comment]
Now hadoop test is failing.

```

14:45:19 > Task :sdks:java:io:hadoop-format:test
14:45:19 
14:45:19 org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOCassandraTest > classMethod FAILED
14:45:19     java.lang.RuntimeException at HadoopFormatIOCassandraTest.java:189
14:45:19         Caused by: java.util.concurrent.ExecutionException at HadoopFormatIOCassandraTest.java:189
14:45:19             Caused by: java.lang.NoSuchFieldError
14:45:19 
14:45:19 org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOCassandraTest > classMethod FAILED
14:45:19     java.lang.NullPointerException at HadoopFormatIOCassandraTest.java:217
```

**Comment by suztomo** [comment]
Now it fails with org.apache.beam.sdk.io.hdfs.HadoopFileSystemRegistrarTest in :sdks:java:io:hadoop-file-system

```
com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at org.apache.hadoop.metrics2.lib.MetricsRegistry.toString(MetricsRegistry.java:406)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.apache.hadoop.ipc.metrics.RpcMetrics.<init>(RpcMetrics.java:74)
	at org.apache.hadoop.ipc.metrics.RpcMetrics.create(RpcMetrics.java:80)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:2218)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:951)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:534)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:509)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:796)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.<init>(NameNodeRpcServer.java:351)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createRpcServer(NameNode.java:674)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:647)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:812)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:796)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1493)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1115)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:986)
	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:815)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:475)
	at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:434)
```

**Comment by suztomo** [comment]
Conflict:

- Bigtable-client-core 1.12.1 needs Guava version >= 23.1 for ImmutableList.builderWithExpectedSize method
- Hadoop-client 2.7.3 needs Guava version <= 20 for Objects.toStringHelper method (note)

Do I have to wait [BEAM-8569 Support Hadoop 3 on Beam](https://issues.apache.org/jira/browse/BEAM-8569)?

**Comment by suztomo** [comment]
Interestingly Hadoop 2.10 does not use `Objects.toStringHelper`.

**Comment by suztomo** [comment]
Now these tests fail:

```
> Task :sdks:java:io:hadoop-format:test
org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOElasticTest > testHifIOWithElastic FAILED
    java.lang.NoClassDefFoundError at HadoopFormatIOElasticTest.java:117
        Caused by: java.lang.ClassNotFoundException at HadoopFormatIOElasticTest.java:117

org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOElasticTest > testHifIOWithElasticQuery FAILED
    java.lang.NoClassDefFoundError at HadoopFormatIOElasticTest.java:163

57 tests completed, 2 failed

> Task :sdks:java:io:hadoop-format:test FAILED
> Task :sdks:java:extensions:sql:test

> Task :sdks:java:io:google-cloud-platform:test

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOStorageReadTest > testReadFromBigQueryIO FAILED
    org.apache.beam.sdk.Pipeline$PipelineExecutionException at BigQueryIOStorageReadTest.java:1529
        Caused by: java.lang.NullPointerException

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOReadTest > testEstimatedSizeWithoutStreamingBuffer FAILED
    java.lang.AssertionError at BigQueryIOReadTest.java:630

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOReadTest > testEstimatedSizeWithStreamingBuffer FAILED
    java.lang.AssertionError at BigQueryIOReadTest.java:664

org.apache.beam.sdk.io.gcp.bigquery.BigQueryUtilTest > testInsertAll FAILED
    java.lang.AssertionError at BigQueryUtilTest.java:212

```

**Comment by suztomo** [comment]
Even with guava:28.1-jre, the following tests fail in io/google-cloud-platform:

```
> Task :sdks:java:io:google-cloud-platform:test

org.apache.beam.sdk.io.gcp.pubsub.PubsubClientTest > timestampAttributeParsesRfc3339WithSmallYear FAILED
    java.lang.AssertionError at PubsubClientTest.java:49

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOStorageReadTest > testReadFromBigQueryIO FAILED
    org.apache.beam.sdk.Pipeline$PipelineExecutionException at BigQueryIOStorageReadTest.java:1529
        Caused by: java.lang.NullPointerException

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOReadTest > testEstimatedSizeWithoutStreamingBuffer FAILED
    java.lang.AssertionError at BigQueryIOReadTest.java:630

org.apache.beam.sdk.io.gcp.bigquery.BigQueryIOReadTest > testEstimatedSizeWithStreamingBuffer FAILED
    java.lang.AssertionError at BigQueryIOReadTest.java:664

org.apache.beam.sdk.io.gcp.bigquery.BigQueryUtilTest > testInsertAll FAILED
    java.lang.AssertionError at BigQueryUtilTest.java:212
```

**Comment by suztomo** [comment]
PubsubClientTest was google-api-client DateTime issue.


BigQuery tests


BigQueryIOStorageReadTest .s 
```
    try (StorageClient client = bqServices.getStorageClient(bqOptions)) {
      CreateReadSessionRequest request = requestBuilder.build();
      readSession = client.createReadSession(request); // returning null
      LOGGER.info(
          "Sent BigQuery Storage API CreateReadSession request '{}'; received response '{}'.",
          request,
          readSession);
    }
```

**Comment by suztomo** [comment]
I track this issue in Beam's JIRA https://issues.apache.org/jira/projects/BEAM/issues/BEAM-8691
go/fixlog in these library upgrades.
