### ISSUE TITLE
Beam to use Guava 28.1-jre

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1040]
https://issues.apache.org/jira/browse/BEAM-5559

The build failed:

```
> Task :sdks:java:io:hadoop-file-system:test FAILED

29 tests completed, 19 failed, 1 skipped

> Task :sdks:java:extensions:sql:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :sdks:java:io:hadoop-format:test

org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOCassandraTest > classMethod FAILED
    java.lang.NoSuchFieldError at HadoopFormatIOCassandraTest.java:189

org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOCassandraTest > classMethod FAILED
    java.lang.NullPointerException at HadoopFormatIOCassandraTest.java:217

57 tests completed, 2 failed

> Task :sdks:java:io:hadoop-format:test FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sdks:java:io:hadoop-file-system:test'.
> There were failing tests. See the report at: file:///usr/local/google/home/suztomo/beam6/sdks/java/io/hadoop-file-system/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sdks:java:io:hadoop-format:test'.
> There were failing tests. See the report at: file:///usr/local/google/home/suztomo/beam6/sdks/java/io/hadoop-format/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7m 1s
462 actionable tasks: 401 executed, 61 up-to-date
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.EOFException: No input provided for project
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: No input provided for project
        at org.apache.tools.ant.Project.defaultInput(Project.java:1305)
        at org.apache.tools.ant.Project.demuxInput(Project.java:1325)
        at org.apache.tools.ant.DemuxInputStream.read(DemuxInputStream.java:71)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more

```

**Comment by suztomo** [comment]
This is blocked by Cassandra: https://issues.apache.org/jira/browse/BEAM-5559?focusedCommentId=16994937&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16994937 . `:sdks:java:io:hadoop-format`'s cassandra dependency requiring old Guava.

Could be done by forcing only `:sdks:java:io:hadoop-format` to use old Guava.

**Comment by suztomo** [comment]
This issue should be tracked in BEAM's JIRA.
