### ISSUE TITLE
Linkage Checker does not detect AbstractMethodError

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1044]
Current Linkage Checker does not detect `AbstractMethodError`, which occurs when an interface method is invoked but the `implement`ing class does not have the method.

https://builds.apache.org/job/beam_PostCommit_Java_PR/246/

```
java.lang.AbstractMethodError: com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.needsCredentials()Z
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.cloud.bigquery.storage.v1beta1.stub.EnhancedBigQueryStorageStub.create(EnhancedBigQueryStorageStub.java:89)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.<init>(BigQueryStorageClient.java:144)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.create(BigQueryStorageClient.java:125)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$StorageClientImpl.<init>(BigQueryServicesImpl.java:1028)
```

- Caller: com.google.api.gax.rpc.ClientContext (com.google.api:gax:1.**48**.0)
- Callee: public final class InstantiatingGrpcChannelProvider implements TransportChannelProvider (in com.google.api:gax-grpc:1.**38**.0)
  This InstantiatingGrpcChannelProvider does not have needsCredentials, which was added to the interface in later version.
- TransportChannelProvider is in com.google.api:gax:1.**48**.0

# AbstractMethodError

https://docs.oracle.com/javase/8/docs/api/java/lang/AbstractMethodError.html

- java.lang.LinkageError
  - java.lang.IncompatibleClassChangeError
    - java.lang.AbstractMethodError

Branch: abstract_method_error

![image](https://user-images.githubusercontent.com/28604/69447199-00b3f980-0d24-11ea-9574-260d815d003c.png)

**Comment by suztomo** [comment]
A solution of this problem is for Apache Beam to use gax-bom. Currently they are not doing it.

**Comment by suztomo** [comment]
- Check all non-abstract class implements interfaces.
- Check all non-abstract class implements interfaces. Error only when methods are referenced. Warn if they're not referenced.

We can check the concrete class's constructor whether it's reachable or not.

Start with 1. Let's see whether it's over-reporting.

**Comment by suztomo** [comment]
As discussed with Elliotte, the data structure of the error

Given:
```
// in J1.jar
class C1 implements I1 {} // empty

// in J2.jar
interface I1 {
  void m1();
  void m2();
}
```

Key:
```
SymbolProblem(
  symbol = MethodSymbol(
    className = C1,
    methodName = m1,
    ... )
  type = AbstractMethod (new entry in enum),
  classFile = J1:C1
),
SymbolProblem(
  symbol = MethodSymbol(
    className = C1,
    methodName = m2,
    ... )
  type = AbstractMethod (new entry in enum),
  classFile = J1:C1
)
```
Value:
```
ClassFile(J2, I1)
```
