### ISSUE TITLE
Linkage Checker fails to resolve Beam's dependency hadoop-client 2.7.3

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1046]
```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-hadoop-common :checkJavaLinkage |tee linkage.log

...

javaee:jboss-servlet-api_3.0:jar:1.0-SNAPSHOT (compile): org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.jboss.javaee:jboss-servlet-api_3.0:jar:1.0-SNAPSHOT in central (http://repo1.maven.org/maven2/)

        at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.levelOrder(DependencyGraphBuilder.java:341)
        at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(DependencyGraphBuilder.java:192)
        at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToDependencyPaths(ClassPathBuilder.java:86)
        at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToClasspath(ClassPathBuilder.java:56)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerArguments.getInputClasspath(LinkageCheckerArguments.java:187)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:50)

```

Detailed log;
https://gist.github.com/suztomo/d51445b3fbaedc1f62904d787f4a4974

Example path:

org.apache.beam:beam-sdks-java-io-hadoop-common:jar:2.18.0-SNAPSHOT (compile)
 / org.apache.hadoop:hadoop-client:jar:2.7.3 (provided)
 / org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.7.3 (compile)
 / org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.7.3 (compile)
 / org.apache.hadoop:hadoop-common:jar:2.7.3 (provided)
 / org.apache.hadoop:hadoop-auth:jar:2.7.3 (compile)
 / org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15 (compile)
 / net.sf.ehcache:ehcache-core:jar:2.4.4 (compile)
 / org.hibernate:hibernate-core:jar:3.5.1-Final (provided)
 / org.jboss.javaee:jboss-jacc-api_JDK4:jar:1.1.0 (provided)
 / org.jboss.javaee:jboss-servlet-api_3.0:jar:1.0-SNAPSHOT (compile)

**Comment by suztomo** [comment]
With 1.1.3, it works. https://gist.github.com/suztomo/5f9d3609c08dd1e502b5751e93d0cf8e
