### ISSUE TITLE
Beam: Linkage Checker gets corrupt JAR file error from amazon-kinesis-client

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1048]
Investigate whether this kind of corruption is skipped or not.

```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-kinesis :checkJavaLinkage |tee linkage.log
Configuration on demand is an incubating feature.

> Task :runners:apex:buildDependencyTree
See the report at: file:///usr/local/google/home/suztomo/beam6/runners/apex/build/classes/java/main/org/apache/beam/runners/apex/dependency-tree

> Task :checkJavaLinkage

> Task :checkJavaLinkage FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings
885 actionable tasks: 156 executed, 729 up-to-date
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.io.IOException: Corrupt jar file /usr/local/google/home/suztomo/.m2/repository/com/amazonaws/amazon-kinesis-client/1.13.0/amazon-kinesis-client-1.13.0.jar; could not load .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:393)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.findSymbolReferences(ClassDumper.java:153)
        at com.google.cloud.tools.opensource.classpath.LinkageChecker.create(LinkageChecker.java:78)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:49)
Caused by: java.lang.ClassNotFoundException: Exception while looking for class .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:77)
        at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:31)
        at com.google.cloud.tools.opensource.classpath.FixedSizeClassPathRepository.loadClass(FixedSizeClassPathRepository.java:108)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:389)
        ... 3 more
Caused by: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.ClassPath.getClassFile(ClassPath.java:666)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckClassPath.getInputStream(LinkageCheckClassPath.java:72)
        at org.apache.bcel.util.ClassPath.getInputStream(ClassPath.java:688)
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:75)
        ... 6 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkJavaLinkage'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

```

**Comment by suztomo** [comment]
I've asked https://github.com/awslabs/amazon-kinesis-client/issues/654 but no answer for now.

**Comment by suztomo** [comment]
As per awslabs/amazon-kinesis-client#654 , the file, prefixed with `/unison` was not supposed to be included in the JAR file.

**Comment by elharo** [comment]
so this isn't really what we were looking for but arguably this was a true positive. At the very least it was a real error.

**Comment by suztomo** [comment]
I'm thinking to skip files prefixed with `/unison` with warning messages.

**Comment by suztomo** [comment]
Discussed with Elliotte. Enhancement:
- LinkageCheckerMain should not die upon this error
- The solution should not be specific to /unison. LinkageChecker is to catch this problem of missing class and log it.
- In future, when we see this JAR file corruption comes again, we'll create a data structure to represent this type of error.
