### ISSUE TITLE
Linkage Monitor to show the dependency path of JAR file in symbol problem

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1081]
Linkage Monitor to show the dependency path of JAR file in symbol problem. (similar to https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1060 , which was done for the dashboard)

As of now, Linkage Monitor does not show the dependency path of JAR file for the symbol in SymbolProblem. For example, in the following error output, the reader cannot tell why it got `google-auth-library-oauth2-http-0.17.1.jar`.

https://source.cloud.google.com/results/invocations/20f5db58-bd1d-42ae-a62c-35159294f76e/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-cloud-bom%2Fpresubmit%2Flinkage-monitor/log

```
SEVERE: Newly introduced problems:
Class com.google.auth.oauth2.QuotaProjectIdProvider is not found
  referenced from com.google.cloud.ServiceOptions (google-cloud-core-1.92.0.jar)
(google-auth-library-oauth2-http-0.17.1.jar) com.google.auth.oauth2.ServiceAccountCredentials's method getQuotaProjectId() is not found
  referenced from com.google.api.gax.core.GoogleCredentialsProvider (gax-1.52.0.jar)
  referenced from com.google.cloud.ServiceOptions (google-cloud-core-1.92.0.jar)
(google-auth-library-oauth2-http-0.17.1.jar) com.google.auth.oauth2.ServiceAccountJwtAccessCredentials$Builder's method setQuotaProjectId(String arg1) is not found
  referenced from com.google.api.gax.core.GoogleCredentialsProvider (gax-1.52.0.jar)
google-cloud-core-1.92.0.jar is at:
  com.google.cloud:google-cloud-core:1.92.0 (compile)
  com.google.cloud:google-cloud-core-grpc:1.92.0 (compile) / com.google.cloud:google-cloud-core:1.92.0 (compile)
  com.google.cloud:google-cloud-core-http:1.92.0 (compile) / com.google.cloud:google-cloud-core:1.92.0 (compile)
gax-1.52.0.jar is at:
  com.google.api:gax:1.52.0 (compile)
  com.google.api:gax-grpc:1.52.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.api:gax-httpjson:0.69.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core:1.92.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-grpc:1.92.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-http:1.92.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-dialogflow:0.119.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-grpc:1.92.0 (compile) / com.google.cloud:google-cloud-core:1.92.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-grpc:1.92.0 (compile) / com.google.api:gax-grpc:1.52.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-http:1.92.0 (compile) / com.google.cloud:google-cloud-core:1.92.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-core-http:1.92.0 (compile) / com.google.api:gax-httpjson:0.69.0 (compile) / com.google.api:gax:1.52.0 (compile)
  com.google.cloud:google-cloud-dialogflow:0.119.0 (compile) / com.google.api:gax-grpc:1.52.0 (compile) / com.google.api:gax:1.52.0 (compile)

Exception in thread "main" com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitorException: Found 3 new linkage errors
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.run(LinkageMonitor.java:192)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.main(LinkageMonitor.java:98)
```

**Comment by elharo** [comment]
Rather than treating this as a single issue, we might do better going back to the drawing board and designing a much more compact and informative display format for linkage errors.

**Comment by suztomo** [comment]
This issue is not about the format/representation of linkage errors, but this is about the information of dependency path to a JAR file.

Still your point makes sense. I created an issue for that. https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1083
