### ISSUE TITLE
LinkageCheckerMain fails to check list of JAR files in v1.1.4

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1340]
Argument: `-j dependencies/src/test/resources/testdata/google-cloud-core-1.48.0.jar,dependencies/src/test/resources/testdata/google-cloud-firestore-0.65.0-beta.jar`. This fails:

```
Exception in thread "main" java.lang.IllegalArgumentException: The arguments must have option 'a' or 'b' to list Maven artifacts
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerArguments.getArtifacts(LinkageCheckerArguments.java:182)
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:54)

```

**Comment by elharo** [comment]
I guess we're missing an integration test for jar files if this bug slipped through.
