### ISSUE TITLE
NullPointerException in IncompatibleLinkageProblem.formatSymbolProblem

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1905]
```
./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-core,beam-sdks-java-io-google-cloud-platform,beam-runners-google-cloud-dataflow-java,beam-sdks-java-io-hadoop-format :checkJavaLinkage
Configuration on demand is an incubating feature.
 
> Task :checkJavaLinkage
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at com.google.cloud.tools.opensource.classpath.IncompatibleLinkageProblem.formatSymbolProblem(IncompatibleLinkageProblem.java:36)
        at com.google.cloud.tools.opensource.classpath.LinkageProblem.lambda$formatLinkageProblems$4(LinkageProblem.java:146)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
        at com.google.cloud.tools.opensource.classpath.LinkageProblem.formatLinkageProblems(LinkageProblem.java:138)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:114)
 
> Task :checkJavaLinkage FAILED
```

**Comment by suztomo** [comment]
I don't see `IncompatibleLinkageProblem.formatSymbolProblem` in IncompatibleLinkageProblem line 36 in master. Asked Kiley to upgrade the version to 1.5.4.

**Comment by suztomo** [comment]
Kiley confirmed 1.5.4 worked fine. Now Beam uses Linkage Checker 1.5.4 https://github.com/apache/beam/pull/13757
