### ISSUE TITLE
Linkage Monitor: Non-resolvable import POM com.google.cloud:google-cloud-spanner-bom:3.2.1

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1925]
When I tried to apply the latest Linkage Monitor at java-spanner, It failed:
https://github.com/googleapis/java-spanner/pull/822

This seems a regression of #1920 . Digging further.

```
INFO: BOM Coordinates: com.google.cloud:libraries-bom:16.3.0
Error: Exception in thread "main" org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for com.google.cloud:libraries-bom:16.3.0
Error:  Non-resolvable import POM com.google.cloud:google-cloud-spanner-bom:3.2.1: Could not find artifact com.google.cloud:google-cloud-spanner-bom:pom:3.3.3-SNAPSHOT @ com.google.cloud:google-cloud-bom:0.147.0

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:498)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:440)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.buildModelWithSnapshotBom(LinkageMonitor.java:397)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.copyWithSnapshot(LinkageMonitor.java:415)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.run(LinkageMonitor.java:230)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.main(LinkageMonitor.java:109)
```

# Log

https://pipelines.actions.githubusercontent.com/CGGwNvwUXlHfGRT2vY2XffB6SGyZVZfhmwVA4PHe1mARap4Khd/_apis/pipelines/1/runs/4602/signedlogcontent/12?urlExpires=2021-01-26T22%3A54%3A14.2614580Z&urlSigningMethod=HMACV1&urlSignature=52ApIUlbflfZxDiydWAfxTbMItbiRUiPzwyVGaJjRHI%3D

It doesn't show it installed the artifacts with Maven.

```
2021-01-26T22:41:50.7766998Z ##[group]Run java -version
2021-01-26T22:41:50.7767709Z [36;1mjava -version[0m
2021-01-26T22:41:50.7818963Z shell: /bin/bash -e {0}
2021-01-26T22:41:50.7819449Z env:
2021-01-26T22:41:50.7820075Z   JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.7820775Z   JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.7821476Z   JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.7822098Z ##[endgroup]
2021-01-26T22:41:50.8657867Z openjdk version "1.8.0_282"
2021-01-26T22:41:50.8660308Z OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
2021-01-26T22:41:50.8661803Z OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
2021-01-26T22:41:50.8733327Z ##[group]Run source .kokoro/common.sh \ retry_with_backoff 3 10 \
2021-01-26T22:41:50.8734158Z [36;1msource .kokoro/common.sh \ retry_with_backoff 3 10 \[0m
2021-01-26T22:41:50.8734791Z [36;1m  mvn install -B -V \[0m
2021-01-26T22:41:50.8735284Z [36;1m -DskipTests=true \[0m
2021-01-26T22:41:50.8735797Z [36;1m -Dclirr.skip=true \[0m
2021-01-26T22:41:50.8736434Z [36;1m -Denforcer.skip=true \[0m
2021-01-26T22:41:50.8737077Z [36;1m -Dmaven.javadoc.skip=true \[0m
2021-01-26T22:41:50.8737810Z [36;1m -Dgcloud.download.skip=true[0m
2021-01-26T22:41:50.8778497Z shell: /bin/bash --noprofile --norc -e -o pipefail {0}
2021-01-26T22:41:50.8779071Z env:
2021-01-26T22:41:50.8779866Z   JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8780576Z   JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8781313Z   JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8781875Z ##[endgroup]
2021-01-26T22:41:50.8941588Z ##[group]Run GoogleCloudPlatform/cloud-opensource-java/linkage-monitor@v1-linkagemonitor
2021-01-26T22:41:50.8942590Z env:
2021-01-26T22:41:50.8943216Z   JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8943903Z   JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8945287Z   JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-26T22:41:50.8945878Z ##[endgroup]
2021-01-26T22:41:50.9350937Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2021-01-26T22:41:50.9352364Z                                  Dload  Upload   Total   Spent    Left  Speed
2021-01-26T22:41:50.9352776Z 
2021-01-26T22:41:50.9476617Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2021-01-26T22:41:51.3729481Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2021-01-26T22:41:51.3851993Z 100 15.6M  100 15.6M    0     0  35.7M      0 --:--:-- --:--:-- --:--:-- 35.6M
2021-01-26T22:41:51.6763655Z SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2021-01-26T22:41:51.6766471Z SLF4J: Defaulting to no-operation (NOP) logger implementation
```

Maybe the `run` parameter cannot take multiple commands? But the document says it supports multi-line commands.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun

```      run: >
        source .kokoro/common.sh \
        retry_with_backoff 3 10 \
          mvn install -B -V \
            -DskipTests=true \
            -Dclirr.skip=true \
            -Denforcer.skip=true \
            -Dmaven.javadoc.skip=true \
            -Dgcloud.download.skip=true
```

**Comment by suztomo** [comment]
It turned out that GitHub Actions did not run `mvn install`. Details in https://github.com/googleapis/java-spanner/pull/822#issuecomment-768363119 , where the ">" replaces new string with space, meaning it was calling `source .kokoro/common.sh retry_with_backoff 3 10 mvn install ...` as one command.

Next time, check the log to ensure previous `mvn install` command run successfully!
