### ISSUE TITLE
LinkageCheckerMain to provide clear error message when the supplied coordinates are invalid

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1948]
When I pass an invalid coordinates to LinkageCheckerMain, it throws `IndexOutOfBoundsException`. This does not tell the cause of the error.

```
> Task :checkJavaLinkage
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IndexOutOfBoundsException: end index (1) must not be greater than size (0)
        at com.google.common.base.Preconditions.checkPositionIndexes(Preconditions.java:1420)
        at com.google.common.collect.ImmutableList.subList(ImmutableList.java:433)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.checkArtifacts(LinkageCheckerMain.java:159)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:66)

> Task :checkJavaLinkage FAILED

```

**Comment by Madanaa** [comment]
@elharo can try this bug

**Comment by NabeelShahid7** [comment]
I would like to work on this issue. @elharo

**Comment by suztomo** [comment]
This issue might be outdated. Check whether the problem still exists or not.

**Comment by Manishpandey11** [comment]
Hi 
I want to contribute by work on this issue
