### ISSUE TITLE
Conflicting gRPC version constraints in spring-cloud-gcp-starter-pubsub

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#347]
The tool cannot build a class path for `org.springframework.cloud:spring-cloud-gcp-starter-pubsub:1.1.0.RC2` in https://repo.spring.io/milestone, because there are two constraints for gRPC version: one for 1.16.1 and the other for 1.15.1.

![image](https://user-images.githubusercontent.com/28604/51278333-49827f80-19a8-11e9-98f4-d329ccd1e150.png)

```

org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies for org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 (compile)

	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:297)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:282)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:121)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:84)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.levelOrder(DependencyGraphBuilder.java:282)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(DependencyGraphBuilder.java:164)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToDependencyPaths(ClassPathBuilder.java:86)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToClasspath(ClassPathBuilder.java:56)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageCheckOptionTest.testConfigureMavenRepositories(StaticLinkageCheckOptionTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.eclipse.aether.collection.UnsolvableVersionConflictException: Could not resolve version conflict among [org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-netty:jar:1.15.1 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-protobuf-lite:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-stub:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-auth:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-okhttp:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-protobuf-nano:jar:1.16.1 -> io.grpc:grpc-core:jar:1.16.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-testing:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1]]
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.newFailure(NearestVersionSelector.java:159)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.backtrack(NearestVersionSelector.java:120)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.selectVersion(NearestVersionSelector.java:93)
	at org.eclipse.aether.util.graph.transformer.ConflictResolver.transformGraph(ConflictResolver.java:181)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:275)
	... 30 more
```

Formatted the error message:

```
[
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 (optional: true)
 -> io.grpc:grpc-netty:jar:1.15.1
 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1],
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 (optional: true)
 -> io.grpc:grpc-services:jar:1.15.1
 -> io.grpc:grpc-protobuf:jar:1.15.1
 -> io.grpc:grpc-core:jar:1.15.1,
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 (optional: true)
 -> io.grpc:grpc-services:jar:1.15.1
 -> io.grpc:grpc-protobuf:jar:1.15.1
 -> io.grpc:grpc-protobuf-lite:jar:1.15.1
 -> io.grpc:grpc-core:jar:1.15.1,
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 (optional: true)
 -> io.grpc:grpc-services:jar:1.15.1
 -> io.grpc:grpc-stub:jar:1.15.1
 -> io.grpc:grpc-core:jar:1.15.1, 
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 (optional: true)
 -> io.grpc:grpc-all:jar:1.16.1 (scope: provided)
 -> io.grpc:grpc-auth:jar:1.16.1
 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1],
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 (optional: true)
 -> io.grpc:grpc-all:jar:1.16.1 (scope: provided)
 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], 
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 (optional: true)
 -> io.grpc:grpc-all:jar:1.16.1 (scope: provided)
 -> io.grpc:grpc-okhttp:jar:1.16.1
 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], 
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 (optional: true)
 -> io.grpc:grpc-all:jar:1.16.1 (scope: provided)
 -> io.grpc:grpc-protobuf-nano:jar:1.16.1
 -> io.grpc:grpc-core:jar:1.16.1,
org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3
 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 (optional: true)
 -> io.grpc:grpc-all:jar:1.16.1 (scope: provided)
 -> io.grpc:grpc-testing:jar:1.16.1
 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1]
]

```

Dependency Path to spring-cloud-sleuth-core:

- 0 = "org.springframework.cloud:spring-cloud-gcp-starter-pubsub:jar:1.1.0.RC2 (compile)"
- 1 = "org.springframework.cloud:spring-cloud-gcp-starter:jar:1.1.0.RC2 (compile)"
- 2 = "org.springframework.cloud:spring-cloud-gcp-autoconfigure:jar:1.1.0.RC2 (compile)"
- 3 = "org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 (compile?)"

spring-cloud-gcp-autoconfigure has following optional dependency:

```
        <!-- Trace -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-core</artifactId>
            <optional>true</optional>
        </dependency>
```

Because this is optional dependency, a Maven project can work with the dependency.

# Maven Version Ranges

A dependency in pom.xml can have a version range, such as `[1.15.1]`, `[3.0, 3.8.2)`

[Versions Maven Plugin /  Resolve Ranges](http://www.mojohaus.org/versions-maven-plugin/examples/resolve-ranges.html)

In case of the conflict above, on one hand, `grpc-netty:1.15.1`, it has following range:

```
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>[1.15.1]</version>
      <scope>compile</scope>
    </dependency>
```

On the other hand, `grpc-all:1.16.1` has following dependency:

```
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>[1.16.1]</version>
      <scope>compile</scope>
    </dependency>
```

Both of the artifacts are 2-hop away from `spring-cloud-sleuth-core:2.1.0.RC3`.

# Report to the owner

From the pom of `spring-cloud-sleuth-core:2.1.0.RC3`, it's not clear which version of gRPC users should pick. `io.github.lognet:grpc-spring-boot-starter:jar:3.0.0` expects 1.15.1, but `io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0` expects 1.16.1.

**Comment by suztomo** [comment]
PR for spring-sleuth created
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1190

**Comment by marcingrzejszczak** [comment]
Fixed via 
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1190

**Comment by elharo** [comment]
Good, please dd this to go/fixlog.

**Comment by suztomo** [comment]
Added to go/fixlog.
