### ISSUE TITLE
ClassPathBuilder to tell total failures rather than exiting immediately

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#355]
As of now  `ClassPathBuilder` fails immediately for one unavailable Maven artifact without telling how many failures need to fix.

Program arguments:
```
-m
https://repo.spring.io/milestone
-a
org.springframework.cloud:spring-cloud-gcp-starter-pubsub:1.1.0.RC2,org.springframework.cloud:spring-cloud-gcp-starter-trace:1.1.0.RC2
```

```
Exception in thread "main" org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies for org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 (compile)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:297)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:282)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:151)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:116)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.levelOrder(DependencyGraphBuilder.java:312)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(DependencyGraphBuilder.java:194)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToDependencyPaths(ClassPathBuilder.java:86)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToClasspath(ClassPathBuilder.java:56)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageCheckOption.generateInputClasspath(StaticLinkageCheckOption.java:141)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageChecker.main(StaticLinkageChecker.java:95)
Caused by: org.eclipse.aether.collection.UnsolvableVersionConflictException: Could not resolve version conflict among [org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-netty:jar:1.15.1 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-protobuf-lite:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-services:jar:1.15.1 -> io.grpc:grpc-stub:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-auth:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-okhttp:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-protobuf-nano:jar:1.16.1 -> io.grpc:grpc-core:jar:1.16.1, org.springframework.cloud:spring-cloud-sleuth-core:jar:2.1.0.RC3 -> io.zipkin.brave:brave-instrumentation-grpc:jar:5.6.0 -> io.grpc:grpc-all:jar:1.16.1 -> io.grpc:grpc-testing:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1]]
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.newFailure(NearestVersionSelector.java:159)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.backtrack(NearestVersionSelector.java:120)
	at org.eclipse.aether.util.graph.transformer.NearestVersionSelector.selectVersion(NearestVersionSelector.java:93)
	at org.eclipse.aether.util.graph.transformer.ConflictResolver.transformGraph(ConflictResolver.java:181)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:275)
	... 9 more

```

**Comment by suztomo** [comment]
# Problem in recursive 
`ClassPathBuilder.levelOrder` may recursively call `resolveCompileTimeDependencies`, which may raise a `DependencyResolutionException`. The exception carries failed artifacts but no `DependencyPath`.

Without DependencyPath, it's difficult how the failure is reached from the root of the first levelOrder call.

# Idea

An exception containing a list of `(DependencyPath, DependencyNode)`

**Comment by suztomo** [comment]
Arguments:

```
-m
https://repo.spring.io/milestone
-a
com.jamonapi:jamon:2.81
```

Shows errors rather than existing the first one.

```
Exception in thread "main" There were failure(s) in dependency resolution
com.jamonapi:jamon:jar:2.81 (compile) / log4j:log4j:jar:1.2.15 (provided) / javax.jms:jms:jar:1.1 (compile): org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact javax.jms:jms:jar:1.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory
com.jamonapi:jamon:jar:2.81 (compile) / log4j:log4j:jar:1.2.15 (provided) / com.sun.jdmk:jmxtools:jar:1.2.1 (compile): org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact javax.jms:jms:jar:1.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory
com.jamonapi:jamon:jar:2.81 (compile) / log4j:log4j:jar:1.2.15 (provided) / com.sun.jmx:jmxri:jar:1.2.1 (compile): org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact javax.jms:jms:jar:1.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory

	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.levelOrder(DependencyGraphBuilder.java:347)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(DependencyGraphBuilder.java:196)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToDependencyPaths(ClassPathBuilder.java:86)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToClasspath(ClassPathBuilder.java:56)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageCheckOption.generateInputClasspath(StaticLinkageCheckOption.java:141)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageChecker.main(StaticLinkageChecker.java:95)
```
