### ISSUE TITLE
Bytebuddy not having ModuleHashesAttribute

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#408]
Classpath checker with `-a net.bytebuddy:byte-buddy:1.9.9` shows following error.

```
byte-buddy-1.9.9.jar (2 errors):
  ClassSymbolReference{sourceClassName=net.bytebuddy.jar.asm.commons.ClassRemapper, targetClassName=net.bytebuddy.jar.asm.commons.ModuleHashesAttribute, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  FieldSymbolReference{sourceClassName=net.bytebuddy.jar.asm.commons.ClassRemapper, targetClassName=net.bytebuddy.jar.asm.commons.ModuleHashesAttribute, fieldName=modules}, reason: CLASS_NOT_FOUND, target class location not found

```

byte-buddy uses maven-shade plugin for ClassRemapper. ([pom.xml](https://github.com/raphw/byte-buddy/blob/419ba8837c6106a8f2c71be024fe5317ab869d94/byte-buddy/pom.xml#L114) for byte-buddy-1.9.3)

```
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>${version.plugin.shade}</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <shadedArtifactAttached>false</shadedArtifactAttached>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <createSourcesJar>true</createSourcesJar>
              <shadeSourcesContent>true</shadeSourcesContent>
              <relocations>
                <relocation>
                  <pattern>${shade.source}</pattern>
                  <shadedPattern>${shade.target}</shadedPattern>
                </relocation>
              </relocations>
              <filters>
                <filter>
                  <artifact>org.ow2.asm:asm-commons</artifact>
                  <includes>
                    <include>org/objectweb/asm/commons/Remapper.class</include>
                    <include>org/objectweb/asm/commons/SimpleRemapper.class</include>
                    <include>org/objectweb/asm/commons/ClassRemapper.class</include>
                    <include>org/objectweb/asm/commons/AnnotationRemapper.class</include>
                    <include>org/objectweb/asm/commons/FieldRemapper.class</include>
                    <include>org/objectweb/asm/commons/MethodRemapper.class</include>
                    <include>org/objectweb/asm/commons/ModuleRemapper.class</include>
                    <include>org/objectweb/asm/commons/SignatureRemapper.class</include>
                  </includes>
                </filter>
              </filters>
              <transformers>
                <transformer>
                  <mainClass>net.bytebuddy.build.Plugin$Engine$Default</mainClass>
                </transformer>
              </transformers>
```

`asm-commons` contains `ClassRemapper.class` and `ModuleHashesAttribute`. But the latter is not included in the maven-shaded-plugin configuration.

![image](https://user-images.githubusercontent.com/28604/52222694-1bd77a80-2872-11e9-8a7a-2b3fe804bea9.png)

# Question to answer

Is this genuine error or false positive?

### Thoughts before investigation

Because the class is explicitly included for maven-shade-plugin, very likely it's used somewhere in bytebuddy (reachability cannot help).

On the other hand, because the dependency `ModuleHashesAttribute` is missing, the class cannot ~~be loaded by a class loader~~ invoke `visitAttribute` method.

## Trying to produce NoClassDefFoundError

Interestingly the following code just works with dependency 

```
        ClassRemapper classRemapper = new ClassRemapper(null, null);
        classRemapper.visitAttribute(null);

# pom.xml
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
      <version>1.9.2</version>
    </dependency>
```

It is supposed to fail with `NoClassDefFoundError`. Why does it work?

```
$ javap -cp `find ~/.m2 -name 'byte-buddy-1.9.2.jar'` -v  net/bytebuddy/jar/asm/commons/ClassRemapper
...
  public void visitAttribute(net.bytebuddy.jar.asm.Attribute);
    descriptor: (Lnet/bytebuddy/jar/asm/Attribute;)V
    flags: ACC_PUBLIC
    Code:
      stack=5, locals=5, args_size=2
         0: aload_1
         1: instanceof    #94                 // class net/bytebuddy/jar/asm/commons/ModuleHashesAttribute
         4: ifeq          64
         7: aload_1
         8: checkcast     #94                 // class net/bytebuddy/jar/asm/commons/ModuleHashesAttribute
        11: astore_2
        12: aload_2
        13: getfield      #98                 // Field net/bytebuddy/jar/asm/commons/ModuleHashesAttribute.modules:Ljava/util/List;
        16: astore_3
        17: iconst_0
        18: istore        4
        20: iload         4


   #93 = Utf8               net/bytebuddy/jar/asm/commons/ModuleHashesAttribute
   #94 = Class              #93           // net/bytebuddy/jar/asm/commons/ModuleHashesAttribute

```

I was able to produce ClassNotFoundException.

```
package net.bytebuddy.jar.asm;
...
  public static void main(String[] args) throws Exception {
    ClassRemapper classRemapper = new ClassRemapper(null, null);
    classRemapper.visitAttribute(new Attribute("hello"));

```

The package is to access package-private Attribute class.

```
Exception in thread "main" java.lang.NoClassDefFoundError: net/bytebuddy/jar/asm/commons/ModuleHashesAttribute
	at net.bytebuddy.jar.asm.commons.ClassRemapper.visitAttribute(ClassRemapper.java:120)
	at net.bytebuddy.jar.asm.App.main(App.java:12)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.ModuleHashesAttribute
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

Lessons learned: instanceof does not throw NoClassDefFoundError if when it checks `null`.

Created a ticket for Byte Buddy: https://github.com/raphw/byte-buddy/issues/608

**Comment by suztomo** [comment]
The issue in byte-buddy is filed in go/fixlog
