### ISSUE TITLE
Fix Windows build

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#480]
For #475 . As of now the test fails with Windows continuous build. Let's fix it.

# Fix: checking suffix of a path (toString)

```
[ERROR] Failures: 
[ERROR]   LinkageCheckerTest.testFindClassReferences_privateClass:619 When the superclass is unavailable, it should report the location of InnerService
expected to end with: testdata/api-common-1.7.0.jar
but was             : T:\src\github\cloud-opensource-java\dependencies\target\test-classes\testdata\api-common-1.7.0.jar
```

# Illegal character ":" for Path

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /T:/src/github/cloud-opensource-java/dashboard/target/classes/css/dashboard.css
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.cloud.tools.opensource.dashboard.DashboardMain.copyResource(DashboardMain.java:146)
	at com.google.cloud.tools.opensource.dashboard.DashboardMain.generateHtml(DashboardMain.java:126)
	at com.google.cloud.tools.opensource.dashboard.DashboardMain.generate(DashboardMain.java:114)
	at com.google.cloud.tools.opensource.dashboard.DashboardTest.setUp(DashboardTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 107.281 s <<< FAILURE! - in com.google.cloud.tools.opensource.dashboard.DashboardTest
[ERROR] com.google.cloud.tools.opensource.dashboard.DashboardTest  Time elapsed: 107.281 s  <<< FAILURE!
java.lang.AssertionError: Could not generate dashboard
	at com.google.cloud.tools.opensource.dashboard.DashboardTest.setUp(DashboardTest.java:87)
```

**Comment by suztomo** [comment]
Fixed as part of #481
