### ISSUE TITLE
Make LinkageChecker faster

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#489]
It seems trying to fetch Maven artifacts from remote repository unnecessarily.

It would take 40000 seconds to fill 167 x 167 table for pair-wise comparison.

```
Running io.grpc:grpc-auth:jar:1.18.0 com.google.cloud:google-cloud-monitoring:jar:1.63.0 (923/27889). ETA: 408741 seconds
Running io.grpc:grpc-auth:jar:1.18.0 com.google.api.grpc:proto-google-cloud-monitoring-v3:jar:1.45.0 (924/27889). ETA: 408741 seconds
Running io.grpc:grpc-auth:jar:1.18.0 com.google.api.grpc:grpc-google-cloud-monitoring-v3:jar:1.45.0 (925/27889). ETA: 408769 seconds
Running io.grpc:grpc-auth:jar:1.18.0 com.google.cloud:google-cloud-os-login:jar:0.81.0-alpha (926/27889). ETA: 408796 seconds
```

**Comment by suztomo** [comment]
It failed

```
Running io.grpc:grpc-alts:jar:1.18.0 com.google.cloud:google-cloud-nio:jar:0.81.0-alpha (717/27889). ETA: 33801 seconds
Exception in thread "main" com.google.common.base.VerifyException: The target class symbol reference is not found in source class
	at com.google.common.base.Verify.verify(Verify.java:124)
	at com.google.cloud.tools.opensource.classpath.ClassDumper.isUnusedClassSymbolReference(ClassDumper.java:585)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.checkLinkageErrorMissingClassAt(LinkageChecker.java:340)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.errorsFromSymbolReferences(LinkageChecker.java:141)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.generateLinkageReport(LinkageChecker.java:110)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.lambda$findLinkageErrors$0(LinkageChecker.java:86)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:186)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.findLinkageErrors(LinkageChecker.java:84)
	at com.google.cloud.tools.opensource.classpath.LeagueTableMain.main(LeagueTableMain.java:93)
```
