### ISSUE TITLE
LinkageChecker unable to check  io.grpc:grpc-alts:jar:1.18.0 com.google.cloud:google-cloud-nio:jar:0.81.0-alpha

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#495]
There seems a bug:

argument
```
-a io.grpc:grpc-alts:jar:1.18.0,com.google.cloud:google-cloud-nio:jar:0.81.0-alpha
```

```
Exception in thread "main" com.google.common.base.VerifyException: The target class symbol reference org.apache.http.client.config.RequestConfig$Builder is not found in source class com.google.api.client.http.apache.ApacheHttpRequest
	at com.google.common.base.Verify.verify(Verify.java:124)
	at com.google.cloud.tools.opensource.classpath.ClassDumper.isUnusedClassSymbolReference(ClassDumper.java:585)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.checkLinkageErrorMissingClassAt(LinkageChecker.java:340)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.errorsFromSymbolReferences(LinkageChecker.java:141)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.generateLinkageReport(LinkageChecker.java:110)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.lambda$findLinkageErrors$0(LinkageChecker.java:86)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:186)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.findLinkageErrors(LinkageChecker.java:84)
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:51)

```

The class com.google.api.client.http.apache.ApacheHttpRequest exists in multiple jar files in the class path:

```
/usr/local/google/home/suztomo/.m2/repository/com/google/http-client/google-http-client/1.19.0/google-http-client-1.19.0.jar contains com.google.api.client.http.apache.ApacheHttpRequest
/usr/local/google/home/suztomo/.m2/repository/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar contains com.google.api.client.http.apache.ApacheHttpRequest
```

**Comment by elharo** [comment]
Is this a bug that should be reported to google-http-java-client?

**Comment by suztomo** [comment]
@elharo This `google-http-client-apache` having `com.google.api.client.http.apache.ApacheHttpRequest` is the same cause of the previously-discussed artifact split of `google-http-client` (https://github.com/googleapis/google-cloud-java/issues/4579).
So not reporting this.

**Comment by elharo** [comment]
So the bug is that this should be reported instead of throwing an exception. Is that correct?
