### ISSUE TITLE
catch ClassFormatException in LinkageChecker

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#536]
So this just happened. BCEL got this wrong. ClassFormatException should be a checked exception because it reads untrusted external data. Regardless we need to catch and handle this case somewhere.

```
org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 60
	at org.apache.bcel.classfile.Constant.readConstant(Constant.java:171)
	at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:66)
	at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:239)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:144)
	at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:131)
	at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:89)
	at com.google.cloud.tools.opensource.classpath.ClassDumper.listClassesInJar(ClassDumper.java:390)
	at com.google.cloud.tools.opensource.classpath.ClassDumper.scanSymbolReferencesInJar(ClassDumper.java:159)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.create(LinkageChecker.java:60)
	at com.google.cloud.tools.opensource.dashboard.DashboardMain.generate(DashboardMain.java:140)
	at com.google.cloud.tools.opensource.dashboard.DashboardMain.generate(DashboardMain.java:124)
	at com.google.cloud.tools.opensource.dashboard.DashboardTest.setUp(DashboardTest.java:91)
```

**Comment by elharo** [comment]
possible root cause: https://stackoverflow.com/questions/6751920/tomcat-7-servlet-3-0-invalid-byte-tag-in-constant-pool

**Comment by elharo** [comment]
java.io.IOException: Possible corrupt jar file /Users/elharo/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar; could not load com.ibm.icu.impl.data.LocaleElements_zh__PINYIN; Invalid byte tag in constant pool: 60

**Comment by elharo** [comment]
More jaxen weirdness:

```
com.google.http-client:google-http-client-findbugs:1.29.0 / com.google.code.findbugs:findbugs:3.0.1 / jaxen:jaxen:1.1.6 / xom:xom:1.0 / com.ibm.icu:icu4j:2.6.1
com.google.http-client:google-http-client-findbugs:1.29.0 / com.google.code.findbugs:findbugs:3.0.1 / dom4j:dom4j:1.6.1 / jaxen:jaxen:1.1-beta-6 / xom:xom:1.0b3 / com.ibm.icu:icu4j:2.6.1
com.google.http-client:google-http-client-findbugs:1.29.0 / com.google.code.findbugs:findbugs:3.0.1 / dom4j:dom4j:1.6.1 / jaxen:jaxen:1.1-beta-6 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / xom:xom:1.0b3 / com.ibm.icu:icu4j:2.6.1
```
