### ISSUE TITLE
grpc-protobuf-lite has many conflicts with google cloud libraries

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#587]
grpc-protobuf-lite has many linkage conflicts with google cloud libraries:

(pair-wise comparison table)
![image](https://user-images.githubusercontent.com/28604/56820327-8b2d8c80-6819-11e9-8fdd-84de200186cf.png)

Linkage checker detects:

```
google-cloud-bigtable-0.84.0-alpha.jar (1 errors):
  com.google.protobuf.UnsafeByteOperations.unsafeWrap is not found, referenced from com.google.cloud.bigtable.data.v2.models.Range$ByteStringRange

proto-google-cloud-bigtable-v2-0.49.0.jar (36 errors):
  com.google.protobuf.AbstractMessageLite$Builder.addAll is not found, referenced from com.google.bigtable.v2.MutateRowsResponse$Builder
  com.google.protobuf.Parser.parseFrom is not found, referenced from com.google.bigtable.v2.Mutation$DeleteFromFamily
...
```

# Example project to produce runtime error

a Maven project to generate a NoSuchMethodError:

```
  <parent>
   <groupId>com.google.cloud</groupId>
  <artifactId>cloud-oss-bom</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf-lite</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-bigtable</artifactId>
    </dependency>
  </dependencies>
```  

Java code:

```
public class App 
{
    public static void main( String[] args )
    {
        Range.ByteStringRange.prefix("foo");        
    }
}
```

Runtime exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.protobuf.UnsafeByteOperations.unsafeWrap([B)Lcom/google/protobuf/ByteString;
	at com.google.cloud.bigtable.data.v2.models.Range$ByteStringRange.prefix(Range.java:363)
	at com.google.cloud.bigtable.data.v2.models.Range$ByteStringRange.prefix(Range.java:336)
	at suztomo.App.main(App.java:16)
```

**Comment by suztomo** [comment]
Posted a question: https://github.com/grpc/grpc-java/issues/5644

**Comment by elharo** [comment]
protobug-lite appears to be intended for android specifically. I'm not 100% sure this should be in the BOM.

**Comment by suztomo** [comment]
Yes, it's for Android. Android apps accessing GCP services may benefit from a future fix.
(I didn't try to reproduce this inconsistency in Android though)

**Comment by suztomo** [comment]
As explained in https://github.com/grpc/grpc-java/issues/5644#issuecomment-487229955, GCP Java libraries are not supported for Android.

**Comment by elharo** [comment]
OK, we need to remove this from the BOM then. We should take out protobuf-nano while we're at it, which isn't used anywhere and is going away in gRPC soon anyway.
