### ISSUE TITLE
Enforcer Rule: StackOverflowError

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#842]
When I applied the enforcer rule to a Google App Engine Java project with Spanner ([suztomo/spring-cloud-gcp-i1815's branch linkage-checker](https://github.com/suztomo/spring-cloud-gcp-i1815/pull/new/linkage-checker)), it threw StackOverflowError.

```
[WARNING] Failure to transfer log4j:log4j/maven-metadata.xml from http://www.terracotta.org/download/reflector/releases was cached in the local repository, resolution will not be reattempted until the update interval of terracotta-releases has elapsed or updates are forced. Original error: Could not transfer metadata log4j:log4j/maven-metadata.xml from/to terracotta-releases (http://www.terracotta.org/download/reflector/releases): Forbidden (403)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.322 s
[INFO] Finished at: 2019-08-15T08:37:54-04:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/google/home/suztomo/local/apache-maven-3.6.1/conf/logging/
constituent[1]: file:/usr/local/google/home/suztomo/local/apache-maven-3.6.1/lib/maven-compat-3.6.1.jar
...
constituent[47]: file:/usr/local/google/home/suztomo/local/apache-maven-3.6.1/lib/error_prone_annotations-2.1.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:341)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
(... omitting 1023 lines ...)
```

To investigate the cause.

**Comment by suztomo** [comment]
Memo:

IntelliJ's breakpoint "pass count" helps to identify suspicious artifacts.

Picking up some portion of stack.

```
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.11 (provided)
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.7 (provided)
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.5 (provided)
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.6 (provided)
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.10 (provided)
org.jruby:yecht:jar:1.0 (compile)
org.jruby:jruby-core:jar:1.7.5 (provided)
```

**Comment by suztomo** [comment]
Identified StackOverflowError bug in Maven https://issues.apache.org/jira/browse/MNG-6737 . 

However, even after this bug is fixed, the enforcer rule for the Google App Engine Java example project with Spanner will fail because of UnsolvableVersionConflictExceptoin on grpc-core versions.

**Comment by suztomo** [comment]
PR created for Maven-resolver https://github.com/apache/maven-resolver/pull/39

**Comment by suztomo** [comment]
The PR has been merged to master, but no new release yet.

**Comment by elharo** [comment]
possibly related: https://issues.apache.org/jira/projects/MRESOLVER/issues/MRESOLVER-38?filter=allopenissues
